/* Notepad menus, browsing dialogs and document prompts. */
static int vd_editor_position(VDWindow *w,int x,int y){int z=w->editor.zoom?w->editor.zoom:1;int row=w->scroll+(y-w->y-47)/(11*z),col=(x-w->x-5-(w->editor.lines?32*z:0))/(8*z);if(row<0)row=0;if(col<0)col=0;const char *p=w->text;while(*p&&row)if(*p++=='\n')row--;while(*p&&*p!='\n'&&col--)p+=ve_next(p,0);return p-w->text;}
static void vd_editor_draw(VDWindow *w,int x,int y,int width,int height){VEState *e=&w->editor;int z=e->zoom?e->zoom:1,a,b;ve_bounds(e,strlen(w->text),&a,&b);if(w->edit_all){a=0;b=strlen(w->text);}
 vd_rect(x,y,width,22,0x243e30);vd_label(x+6,y+7,"File",VD_TEXT_COLOR,46);vd_label(x+62,y+7,"Edit",VD_TEXT_COLOR,46);vd_label(x+118,y+7,"View",VD_TEXT_COLOR,46);vd_label(x+180,y+7,ve_hash(w->text)==e->clean?"Saved":"Modified",VD_ACCENT,width-180);
 int gutter=e->lines?32*z:0;const char *p=w->text;int skip=w->scroll,line=1;while(*p&&skip){if(*p++=='\n'){skip--;line++;}}
 for(int row=0;row*11*z+8*z<height-26;row++,line++){int yy=y+26+row*11*z,col=0;if(e->lines){char n[16];snprintf(n,sizeof(n),"%d",line);vd_label(x,yy,n,VD_ACCENT,gutter-2);}while(*p&&*p!='\n'){int index=p-w->text;if((col+1)*8*z<=width-gutter){if(index>=a&&index<b)vd_rect(x+gutter+col*8*z,yy,8*z,10*z,0x43684c);vd_char(x+gutter+col*8*z,yy,(unsigned char)*p<128?*p:'?',VD_TEXT_COLOR,z);if(index==w->cursor)vd_rect(x+gutter+col*8*z,yy,1,9*z,VD_ACCENT);}col++;p+=ve_next(p,0);}if(p-w->text==w->cursor&&col*8*z<width-gutter)vd_rect(x+gutter+col*8*z,yy,1,9*z,VD_ACCENT);if(!*p)break;p++;}
 if(w->entry_mode)vd_label(x,y+height-12,w->input,VD_ACCENT,width);
 if(w->edit_menu){static const char *file[]={"New","Open...","Save","Save As..."},*edit[]={"Undo","Redo","Select All","Copy","Cut","Paste","Find...","Replace all...","Find next"},*view[]={"Font -","Font +","Line numbers"};int count=w->edit_menu==1?4:w->edit_menu==2?9:3,mx=x+(w->edit_menu-1)*56,cw=w->edit_menu==2?(width-56)/2:160;if(cw>160)cw=160;vd_rect(mx,y+22,cw*(w->edit_menu==2?2:1),(w->edit_menu==2?5:count)*26,0x294634);for(int j=0;j<count;j++)vd_label(mx+8+(w->edit_menu==2?j/5*cw:0),y+30+(w->edit_menu==2?j%5:j)*26,w->edit_menu==1?file[j]:w->edit_menu==2?edit[j]:view[j],VD_TEXT_COLOR,cw-16);}
 if(e->confirm){int cy=y+50;vd_rect(x+10,cy,width-20,72,0x31563c);vd_label(x+18,cy+8,"Save changes before continuing?",VD_TEXT_COLOR,width-36);vd_button(x+18,cy+38,62,"Save");vd_button(x+86,cy+38,78,"Discard");vd_button(x+170,cy+38,70,"Cancel");}
}
static void vd_editor_picker(VDWindow *w,bool save){if(w->pending){vd_notice("Wait for the document operation to finish");return;}vd.picker_build=true;int i=vd_new(VD_FILES);vd.picker_build=false;if(i<0)return;VDWindow *p=&vd.windows[i];p->picker_owner=w-vd.windows;p->picker_mode=save?2:1;snprintf(p->title,sizeof(p->title),"%s",save?"Save As":"Open file");strcpy(p->path,w->path);char *slash=strrchr(p->path,'/');if(slash){if(save)snprintf(p->input,sizeof(p->input),"%s",slash+1);if(slash==p->path)slash[1]=0;else *slash=0;}else strcpy(p->path,PLAT_GUEST_STORAGE);p->selection=-1;p->scroll=0;vd_request(p,"list",p->path,NULL,NULL,NULL);vd.keyboard=false;}
static void vd_editor_continue(VDWindow *w,int action){w->editor.confirm=0;if(action==1){ve_record(&w->editor,w->text,w->cursor,plat_us(),true);w->text[0]=0;w->cursor=0;w->editor.anchor=w->editor.end=0;w->editor.clean=ve_hash("");strcpy(w->path,PLAT_GUEST_STORAGE "/notes.txt");}else if(action==2)vd_editor_picker(w,false);else if(action==3){w->editor.clean=ve_hash(w->text);vd_close(w-vd.windows);}vd.dirty=true;}
static void vd_editor_intent(VDWindow *w,int action){if(w->pending){vd_notice("Wait for the document operation to finish");return;}if(ve_hash(w->text)!=w->editor.clean){w->editor.confirm=action;w->edit_menu=0;vd.keyboard=false;vd.focused=w-vd.windows;vd.dirty=true;}else vd_editor_continue(w,action);}
static void vd_picker_draw(VDWindow *w,int x,int y,int width,int height){vd_label(x,y+3,w->path,VD_ACCENT,width-104);vd_button(x+width-100,y,46,"^Pg");vd_button(x+width-50,y,46,"vPg");const char *p=w->text;int skip=w->scroll;while(*p&&skip)if(*p++=='\n')skip--;int row=0;while(*p&&row*22<height-80){char name[256];int n=0;while(*p&&*p!='\n'){if(n<255)name[n++]=*p;p++;}name[n]=0;if(*p)p++;int yy=y+22+row*22;vd_rect(x,yy,width,20,row+w->scroll==w->selection?0x477647:0x243e30);vd_label(x+6,yy+6,name,VD_TEXT_COLOR,width-12);row++;}
 if(w->picker_mode==2)vd_label(x,y+height-52,w->input,VD_ACCENT,width);
 const char *labels[]={w->picker_mode==2?"Save":"Open","Up",PLAT_STORAGE_LABEL,"Root","Name","Cancel"};int bw=width/6;for(int i=0;i<6;i++)vd_button(x+i*bw,y+height-25,bw-3,labels[i]);
 if(w->picker_overwrite){vd_rect(x+8,y+45,width-16,70,0x31563c);vd_label(x+16,y+54,"File exists. Replace it?",VD_TEXT_COLOR,width-32);vd_button(x+16,y+83,80,"Replace");vd_button(x+102,y+83,80,"Cancel");}
}
static bool vd_picker_commit(VDWindow *p,const char *path){if(p->picker_owner<0||p->picker_owner>=VD_MAX||!vd.windows[p->picker_owner].used||vd.windows[p->picker_owner].app!=VD_EDIT){vd_notice("Document closed");return false;}VDWindow *w=&vd.windows[p->picker_owner];if(!vd_path_copy(w->path,sizeof(w->path),path))return false;vd.focused=p->picker_owner;if(p->picker_mode==2){w->save_hash=ve_hash(w->text);vd_request(w,"write",w->path,w->text,NULL,NULL);}else vd_request(w,"read",w->path,NULL,NULL,NULL);int owner=p->picker_owner;vd_close(p-vd.windows);vd.focused=owner;vd.keyboard=false;return true;}
static bool vd_picker_click(VDWindow *p,int x,int y){int rx=x-p->x-5,ry=y-p->y-21,width=p->w-10,height=p->h-27;if(p->picker_overwrite){if(ry>=83&&ry<100){if(rx>=16&&rx<96)vd_picker_commit(p,p->picker_target);else if(rx>=102&&rx<182)p->picker_overwrite=false;}
 vd.dirty=true;return true;}if(p->pending){vd_notice("Loading folder...");return true;}
 if(ry<18&&rx>=width-100){int rows=(height-80)/22;if(rx<width-50){p->scroll-=rows;if(p->scroll<0)p->scroll=0;}else{int count=1;for(const char *q=p->text;*q;q++)if(*q=='\n')count++;if(p->scroll+rows<count)p->scroll+=rows;}vd.dirty=true;return true;}
 if(ry>=height-28){int button=rx/(width/6);if(button==5){vd_close(p-vd.windows);vd.keyboard=false;return true;}if(button==1||button==2||button==3){if(button==1){char *slash=strrchr(p->path,'/');if(slash&&slash!=p->path)*slash=0;else strcpy(p->path,"/");}else strcpy(p->path,button==2?PLAT_GUEST_STORAGE:"/root");p->selection=-1;p->scroll=0;vd_request(p,"list",p->path,NULL,NULL,NULL);}else if(button==4&&p->picker_mode==2){p->entry_mode=12;vd.keyboard=true;}else if(button==0){char selected[1024];vd_selected_path(p,selected,sizeof(selected));const char *line=p->text;int row=p->selection;while(*line&&row>0)if(*line++=='\n')row--;if(p->selection>=0&&*line=='D'){if(vd_path_copy(p->path,sizeof(p->path),selected)){p->selection=-1;p->scroll=0;vd_request(p,"list",p->path,NULL,NULL,NULL);}}else if(p->picker_mode==1){if(selected[0])vd_picker_commit(p,selected);else vd_notice("Select a file");}else {if(!p->input[0]||strchr(p->input,'/')||strchr(p->input,'\\')||strchr(p->input,':')||!strcmp(p->input,".")||!strcmp(p->input,"..")){vd_notice("Enter a filename using Name");return true;}char target[1024];if(strlen(p->path)+strlen(p->input)+2>sizeof(p->picker_target)||strlen(p->input)>255){vd_notice("Path or filename is too long");return true;}snprintf(target,sizeof(target),"%s/%.255s",p->path,p->input);if(!vd_path_copy(p->picker_target,sizeof(p->picker_target),target))return true;vd_request(p,"exists",p->picker_target,NULL,NULL,NULL);}}}
 else if(ry>=22&&ry<height-60){p->selection=p->scroll+(ry-22)/22;char selected[1024];vd_selected_path(p,selected,sizeof(selected));const char *base=strrchr(selected,'/');if(p->picker_mode==2&&base)snprintf(p->input,sizeof(p->input),"%s",base+1);}
 vd.dirty=true;return true;}
static bool vd_notepad_click(VDWindow *w,int x,int y){int rx=x-w->x-5,ry=y-w->y-21;VEState *e=&w->editor;
 if(e->confirm){if(ry>=88&&ry<104){int action=e->confirm;if(rx>=18&&rx<80){e->after_save=action;e->confirm=0;w->save_hash=ve_hash(w->text);vd_request(w,"write",w->path,w->text,NULL,NULL);}else if(rx>=86&&rx<164)vd_editor_continue(w,action);else if(rx>=170&&rx<240)e->confirm=0;}
 vd.dirty=true;return true;}
 if(ry>=0&&ry<22){w->edit_menu=rx<56?1:rx<112?2:rx<168?3:0;vd.keyboard=false;return true;}
 if(!w->edit_menu)return false;
 int mx=(w->edit_menu-1)*56,menu=w->edit_menu;w->edit_menu=0;int count=menu==1?4:menu==2?9:3,cw=menu==2?(w->w-66)/2:160;if(cw>160)cw=160;int rows=menu==2?5:count;if(rx<mx||rx>=mx+cw*(menu==2?2:1)||ry<22||ry>=22+rows*26)return true;int action=(ry-22)/26+(menu==2?(rx-mx)/cw*5:0);if(action>=count)return true;
 if(menu==1){if(action==0)vd_editor_intent(w,1);else if(action==1)vd_editor_intent(w,2);else if(action==2)vd_action(w,0);else vd_editor_picker(w,true);}
 else if(menu==2){unsigned char codes[]={26,25,1,3,24,22};if(action<6)desktop_input_byte(codes[action]);else if(action==8){if(!ve_find(e,w->text,&w->cursor))vd_notice("Text not found");}else {w->entry_mode=action==6?9:10;w->input[0]=0;vd.keyboard=true;vd_notice(action==6?"Find text, then Enter":"Text to replace, then Enter");}}
 else if(action==2)e->lines=!e->lines;else {e->zoom+=action==0?-1:1;if(e->zoom<1)e->zoom=1;if(e->zoom>2)e->zoom=2;}
 vd.dirty=true;return true;}
