static void vd_solitaire_card(VGState *g,int x,int y,int width,int height,int card,bool face,bool selected){vd_rect(x,y,width-3,height,selected?0x88c572:face?0xe2efe6:0x31563c);if(face){char label[16];const char *ranks=" A23456789TJQK",*suits="CDHS";snprintf(label,sizeof(label),"%c%c",ranks[vg_rank(card)],suits[card/13]);vd_label(x+3,y+3,label,vg_red(card)?0x903333:0x10241d,width-8);}}
static int vd_solitaire_stride(const VGState *g,int bh,int col){int open=g->card_count[col]-g->face[col],stride=open>1?(bh-78-g->face[col]*3)/(open-1):16;if(stride>16)stride=16;if(stride<8)stride=8;return stride;}
static void vd_solitaire_draw(VGState *g,int x,int y,int width,int bh){int cw=width/7;vd_rect(x,y,width,bh,0x0c1d15);vd_solitaire_card(g,x,y,cw,34,0,false,false);vd_label(x+3,y+17,g->stock_count?"Deal":"Recycle",VD_ACCENT,cw-6);if(g->waste_count)vd_solitaire_card(g,x+cw,y,cw,34,g->waste[g->waste_count-1],true,g->card_source==7);for(int suit=0;suit<4;suit++){int xx=x+(suit+3)*cw;if(g->foundation[suit])vd_solitaire_card(g,xx,y,cw,34,suit*13+g->foundation[suit]-1,true,false);else{char label[2]={"CDHS"[suit],0};vd_rect(xx,y,cw-3,34,0x294634);vd_label(xx+4,y+5,label,VD_ACCENT,cw-8);}}for(int col=0;col<7;col++){int stride=vd_solitaire_stride(g,bh,col);int xx=x+col*cw;if(!g->card_count[col])vd_rect(xx,y+44,cw-3,32,0x294634);for(int row=0;row<g->card_count[col];row++)vd_solitaire_card(g,xx,y+44+(row<g->face[col]?row*3:g->face[col]*3+(row-g->face[col])*stride),cw,row==g->card_count[col]-1?34:row<g->face[col]?3:stride,g->cards[col][row],row>=g->face[col],g->card_source==col&&row>=g->card_row);}}
static void vd_solitaire_click(VGState *g,int x,int y,int width,int bh){if(x<0||x>=width||y<0||y>=bh)return;int col=x/(width/7);if(col>6)return;if(y<36){if(col==0)vg_sol_deal(g);else if(col==1)vg_sol_select(g,7,0);else if(col>=3)vg_sol_move(g,7+col-3);}else if(y>=44){if(g->card_source>=0&&vg_sol_move(g,col))return;int offset=y-44-g->face[col]*3;if(offset<0)return;int row=g->face[col]+offset/vd_solitaire_stride(g,bh,col);if(row>=g->card_count[col])row=g->card_count[col]-1;vg_sol_select(g,col,row);}}
static void vd_games_draw(VDWindow *w,int x,int y,int width,int height){
 VGState *g=&w->game;const char *names[]={"Games","Snake","Falling Blocks","Brick Breaker","Minesweeper","Pong","2048","Solitaire"};
 if(!g->kind){vd_label(x,y+5,"Games folder - native Vita games",VD_ACCENT,width);int cell=(width-8)/2;for(int i=1;i<=7;i++){int xx=x+((i-1)%2)*(cell+8),yy=y+30+((i-1)/2)*37;vd_rect(xx,yy,cell,32,0x31563c);vd_label(xx+10,yy+12,names[i],VD_TEXT_COLOR,cell-20);}vd_label(x,y+184,"Touch / D-pad. Pause, difficulty and high scores.",VD_ACCENT,width);return;}
 vd_button(x,y,62,"Games");vd_button(x+66,y,78,"Restart");vd_button(x+148,y,62,g->paused?"Resume":"Pause");
 if(g->kind<=3||g->kind==5)vd_button(x+214,y,100,g->difficulty==0?"Easy":g->difficulty==1?"Normal":"Hard");
 char label[120];snprintf(label,sizeof(label),"%s  Score %d  Best %d%s",names[g->kind],g->score,g->best,g->over?"  Game over":g->paused?"  Paused":"");vd_label(x,y+23,label,VD_ACCENT,width);
 int top=y+38,bottom=y+height-28,bh=bottom-top;
 if(g->kind==1||g->kind==2){int cols=g->kind==1?20:10,rows=g->kind==1?14:16,cell=bh/rows;if(cell>width/cols)cell=width/cols;if(cell<1)cell=1;int left=x+(width-cols*cell)/2;vd_rect(left,top,cols*cell,rows*cell,0x0c1d15);
  if(g->kind==1){vd_rect(left+g->food_x*cell,top+g->food_y*cell,cell-1,cell-1,0xdf8352);for(int i=0;i<g->len;i++)vd_rect(left+g->sx[i]*cell,top+g->sy[i]*cell,cell-1,cell-1,i?0x79ac69:0xc6ed9b);}
  else {for(int yy=0;yy<16;yy++)for(int xx=0;xx<10;xx++)if(g->grid[yy][xx])vd_rect(left+xx*cell,top+yy*cell,cell-1,cell-1,0x88c572);if(!g->over)for(int yy=0;yy<4;yy++)for(int xx=0;xx<4;xx++)if(vg_cell(g,xx,yy))vd_rect(left+(g->x+xx)*cell,top+(g->y+yy)*cell,cell-1,cell-1,0xe2c679);}
 }else if(g->kind==7){vd_solitaire_draw(g,x,top,width,bh);}
 else if(g->kind==4||g->kind==6){int cols=g->kind==4?8:4,cell=bh/cols;if(cell>width/cols)cell=width/cols;int left=x+(width-cols*cell)/2;for(int yy=0;yy<cols;yy++)for(int xx=0;xx<cols;xx++){int px=left+xx*cell,py=top+yy*cell;unsigned value=g->kind==4?g->grid[yy][xx]:g->tiles[yy*4+xx];vd_rect(px,py,cell-2,cell-2,g->kind==4&&(value&32)?0x385040:0x31563c);char text[24]={0};if(g->kind==6){if(value)snprintf(text,sizeof(text),"%u",value);}else if(value&64)strcpy(text,"F");else if((value&16)&&((value&32)||g->over))strcpy(text,"*");else if(value&32){if(value&15)snprintf(text,sizeof(text),"%d",value&15);}vd_label(px+3,py+cell/2-4,text,VD_TEXT_COLOR,cell-4);}}
 else if(g->kind==5){vd_rect(x,top,width,bh,0x0c1d15);vd_rect(x+6,top+g->paddle*bh/180,4,40*bh/180,VD_ACCENT);vd_rect(x+width-10,top+g->enemy*bh/180,4,40*bh/180,VD_ACCENT);vd_rect(x+(int)g->ball_x*width/280-2,top+(int)g->ball_y*bh/180-2,4,4,VD_TEXT_COLOR);}
 else{vd_rect(x,top,width,bh,0x0c1d15);for(int yy=0;yy<4;yy++)for(int xx=0;xx<10;xx++)if(g->grid[yy][xx])vd_rect(x+xx*width/10+1,top+(25+yy*14)*bh/180,width/10-2,12*bh/180,0x88c572);vd_rect(x+g->paddle*width/280,top+168*bh/180,60*width/280,4,VD_TEXT_COLOR);vd_rect(x+(int)g->ball_x*width/280-2,top+(int)g->ball_y*bh/180-2,4,4,0xe2c679);}
 const char *keys[]={"Left","Down","Up","Right",g->kind==4?(g->flag_mode?"Reveal":"Flag"):"Drop"};if(g->kind==7){vd_button(x,y+height-20,62,"Deal");vd_label(x+68,y+height-16,"Tap a card/stack, then its destination",VD_ACCENT,width-68);}else if(g->kind==4)vd_button(x,y+height-20,92,g->flag_mode?"Reveal mode":"Flag mode");else for(int i=0;i<(g->kind==2?5:4);i++)if(g->kind!=5||i==1||i==2)vd_button(x+i*58,y+height-20,54,keys[i]);
}
static void vd_games_save(VGState *g){if(g->score>g->best)g->best=g->score;char path[200];snprintf(path,sizeof(path),PLAT_SD "verdant/games/high-score-%d.txt",g->kind);FILE *f=fopen(path,"rb");int best=0;if(f){if(fscanf(f,"%d",&best)!=1)best=0;fclose(f);}if(g->score>best){f=fopen(path,"wb");if(f){fprintf(f,"%d\n",g->score);fclose(f);}}}
static void vd_games_click(VDWindow *w,int x,int y){VGState *g=&w->game;int rx=x-w->x-5,ry=y-w->y-21,height=w->h-27;
 if(!g->kind){if(ry>=30&&ry<178){int cell=(w->w-18)/2,col=rx/(cell+8);int kind=(ry-30)/37*2+col+1;if(col<2&&kind<=7)vg_start(g,kind,(uint32_t)plat_us());}vd.dirty=true;return;}
 if(ry<18){if(rx<66){vd_games_save(g);g->kind=0;}else if(rx<148){vd_games_save(g);int difficulty=g->difficulty;vg_start(g,g->kind,(uint32_t)plat_us());g->difficulty=difficulty;}else if(rx<210)g->paused=!g->paused;else if(rx<314&&(g->kind<=3||g->kind==5))g->difficulty=(g->difficulty+1)%3;}
 else if(ry>=height-22){if(g->kind==7){if(rx<62)vg_sol_deal(g);}else if(g->kind==4){if(rx<92)vg_control(g,4);}else {int key=rx/58;if(key>=0&&key<5)vg_control(g,key);}}
 else if(g->kind==7){vd_solitaire_click(g,rx,ry-38,w->w-10,height-66);}
 else if(g->kind==4){int bh=height-66,cell=bh/8;if(cell>(w->w-10)/8)cell=(w->w-10)/8;int left=((w->w-10)-8*cell)/2;if(rx>=left&&rx<left+8*cell&&ry>=38&&ry<38+8*cell)vg_mines_touch(g,(rx-left)/cell,(ry-38)/cell);}
 else if(g->kind==5){g->paddle=(ry-38)*180/(height-66)-20;if(g->paddle<0)g->paddle=0;if(g->paddle>140)g->paddle=140;}
 else if(g->kind==3){g->paddle=rx*280/(w->w-10)-30;if(g->paddle<0)g->paddle=0;if(g->paddle>220)g->paddle=220;}
 vd.dirty=true;
}
static void vd_games_load_best(VGState *g){char path[200];snprintf(path,sizeof(path),PLAT_SD "verdant/games/high-score-%d.txt",g->kind);FILE *f=fopen(path,"rb");if(f){if(fscanf(f,"%d",&g->best)!=1)g->best=0;fclose(f);}g->best_loaded=true;}
static void vd_games_tick(const plat_input_t *in){uint64_t now=plat_us();for(int i=0;i<VD_MAX;i++){VDWindow *w=&vd.windows[i];if(!w->used||w->app!=VD_GAMES)continue;VGState *g=&w->game;if(g->kind&&!g->best_loaded)vd_games_load_best(g);if(vd_window_obscured(i)||g->paused||g->over||!g->kind){g->tick=now;continue;}if(i==vd.focused){bool repeat=now-g->control_tick>=120000;unsigned keys=in->down;if(repeat)keys|=in->held&(PLAT_BTN_LEFT|PLAT_BTN_DOWN|PLAT_BTN_RIGHT|(g->kind==5?PLAT_BTN_UP:0));if(keys&(PLAT_BTN_LEFT|PLAT_BTN_DOWN|PLAT_BTN_UP|PLAT_BTN_RIGHT)){if(keys&PLAT_BTN_LEFT)vg_control(g,0);if(keys&PLAT_BTN_DOWN)vg_control(g,1);if(keys&PLAT_BTN_UP)vg_control(g,2);if(keys&PLAT_BTN_RIGHT)vg_control(g,3);g->control_tick=now;vd.dirty=true;}
 if(in->ptr_down && !vd.keyboard){int tx=(in->ptr_x+vd.touch_offset_x)*VD_W/PLAT_TERM_W,ty=(in->ptr_y+PLAT_TERM_H+vd.touch_offset_y)*VD_H/(PLAT_TERM_H+PLAT_PANEL_H);bool inside=tx>=w->x+5&&tx<w->x+w->w-5&&ty>=w->y+59&&ty<w->y+w->h-49;if(inside&&(g->kind==3||g->kind==5)){vd_games_click(w,tx,ty);g->control_tick=now;}else if(repeat&&tx>=w->x+5&&tx<w->x+w->w-5&&ty>=w->y+w->h-49&&ty<w->y+w->h-27){int key=(tx-w->x-5)/58;if(key<4&&(key!=2||g->kind==5)){vg_control(g,key);g->control_tick=now;vd.dirty=true;}}}
 }
 if(g->kind==4||g->kind==6||g->kind==7)continue;
 uint64_t interval=g->kind==1?180000:g->kind==2?600000:20000;interval=interval*(3-g->difficulty)/3;if(!g->tick)g->tick=now;if(now-g->tick>=interval){g->tick=now;vg_step(g);if(g->over)vd_games_save(g);vd.dirty=true;}}
}
