#ifndef VERDANT_GAMES_H
#define VERDANT_GAMES_H
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
typedef struct {int kind,score,len,dir,next,food_x,food_y,x,y,shape,rotation,paddle;int difficulty,best,enemy,lives;uint64_t control_tick;bool paused,over,won,best_loaded,flag_mode,mines_seeded;uint32_t tiles[16];unsigned char cards[7][20],card_count[7],face[7],stock[24],waste[24],foundation[4];int stock_count,waste_count,card_source,card_row;uint32_t random;uint64_t tick;unsigned char grid[16][20],sx[280],sy[280];float ball_x,ball_y,dx,dy;} VGState;
static uint32_t vg_random(VGState *g){g->random=g->random*1664525u+1013904223u;return g->random;}
static void vg_food(VGState *g){int empty[280],count=0;for(int y=0;y<14;y++)for(int x=0;x<20;x++){bool used=false;for(int i=0;i<g->len;i++)if(g->sx[i]==x&&g->sy[i]==y)used=true;if(!used)empty[count++]=y*20+x;}if(!count){g->over=true;return;}int cell=empty[vg_random(g)%count];g->food_x=cell%20;g->food_y=cell/20;}
#include "solitaire.h"
static const uint16_t vg_shapes[]={0x00f0,0x0066,0x0072,0x0036,0x0063,0x0071,0x0074};
static bool vg_cell(const VGState *g,int x,int y){for(int r=0;r<(g->rotation%4);r++){int tmp=x;x=y;y=3-tmp;}return (vg_shapes[g->shape]>>(y*4+x))&1;}
static bool vg_fits(VGState *g,int x,int y){for(int yy=0;yy<4;yy++)for(int xx=0;xx<4;xx++)if(vg_cell(g,xx,yy)){int dx=x+xx,dy=y+yy;if(dx<0||dx>=10||dy<0||dy>=16||g->grid[dy][dx])return false;}return true;}
static void vg_spawn(VGState *g){g->shape=(int)(vg_random(g)%7);g->rotation=0;g->x=3;g->y=0;if(!vg_fits(g,g->x,g->y))g->over=true;}
static void vg_tile_spawn(VGState *g){int empty[16],n=0;for(int i=0;i<16;i++)if(!g->tiles[i])empty[n++]=i;if(n)g->tiles[empty[vg_random(g)%n]]=(vg_random(g)%10)?2:4;}
static void vg_mines_seed(VGState *g,int safe){int placed=0;while(placed<10){int cell=vg_random(g)%64;if(cell==safe || (g->grid[cell/8][cell%8]&16))continue;g->grid[cell/8][cell%8]=16;placed++;}for(int y=0;y<8;y++)for(int x=0;x<8;x++)if(!(g->grid[y][x]&16)){int count=0;for(int yy=y-1;yy<=y+1;yy++)for(int xx=x-1;xx<=x+1;xx++)if(xx>=0&&xx<8&&yy>=0&&yy<8&&(g->grid[yy][xx]&16))count++;g->grid[y][x]=count;}g->mines_seeded=true;}
static void vg_mines_touch(VGState *g,int x,int y){if(g->paused||g->over||x<0||x>=8||y<0||y>=8)return;if(g->flag_mode){if(!(g->grid[y][x]&32))g->grid[y][x]^=64;return;}if(g->grid[y][x]&64)return;if(!g->mines_seeded)vg_mines_seed(g,y*8+x);if(g->grid[y][x]&16){g->grid[y][x]|=32;g->over=true;return;}int queue[64],read=0,write=0;g->grid[y][x]|=32;queue[write++]=y*8+x;while(read<write){int cell=queue[read++],cx=cell%8,cy=cell/8;if(g->grid[cy][cx]&15)continue;for(int yy=cy-1;yy<=cy+1;yy++)for(int xx=cx-1;xx<=cx+1;xx++)if(xx>=0&&xx<8&&yy>=0&&yy<8&&!(g->grid[yy][xx]&(16|32|64))){g->grid[yy][xx]|=32;queue[write++]=yy*8+xx;}}int seen=0;for(int yy=0;yy<8;yy++)for(int xx=0;xx<8;xx++)if(g->grid[yy][xx]&32)seen++;g->score=seen*10;if(seen==54)g->won=g->over=true;}
static void vg_tile_move(VGState *g,int key){uint32_t old[16];memcpy(old,g->tiles,sizeof(old));for(int line=0;line<4;line++){int index[4];uint32_t compact[4]={0},merged[4]={0};int n=0,m=0;for(int pos=0;pos<4;pos++){int x=(key==0||key==3)?(key==0?pos:3-pos):line,y=(key==0||key==3)?line:(key==2?pos:3-pos);index[pos]=y*4+x;if(g->tiles[index[pos]])compact[n++]=g->tiles[index[pos]];}for(int i=0;i<n;i++){uint32_t value=compact[i];if(i+1<n&&compact[i+1]==value&&value<=0x10000000u){value*=2;g->score+=(int)value;i++;}merged[m++]=value;}for(int pos=0;pos<4;pos++)g->tiles[index[pos]]=merged[pos];}if(memcmp(old,g->tiles,sizeof(old)))vg_tile_spawn(g);bool can=false;for(int y=0;y<4;y++)for(int x=0;x<4;x++){uint32_t value=g->tiles[y*4+x];if(!value||(x<3&&value==g->tiles[y*4+x+1])||(y<3&&value==g->tiles[(y+1)*4+x]))can=true;}if(!can)g->over=true;}
static void vg_start(VGState *g,int kind,uint32_t seed){memset(g,0,sizeof(*g));g->kind=kind;g->random=seed;g->dir=g->next=3;g->len=4;for(int i=0;i<4;i++){g->sx[i]=8-i;g->sy[i]=7;}if(kind==1)vg_food(g);if(kind==2)vg_spawn(g);if(kind==7)vg_sol_start(g);if(kind==6){vg_tile_spawn(g);vg_tile_spawn(g);}if(kind==5){g->paddle=g->enemy=70;g->ball_x=140;g->ball_y=90;g->dx=2;g->dy=1;g->lives=3;}if(kind==3){g->paddle=110;g->ball_x=140;g->ball_y=150;g->dx=2;g->dy=-2;for(int y=0;y<4;y++)for(int x=0;x<10;x++)g->grid[y][x]=1;}}
static void vg_lock(VGState *g){for(int y=0;y<4;y++)for(int x=0;x<4;x++)if(vg_cell(g,x,y))g->grid[g->y+y][g->x+x]=(unsigned char)(g->shape+1);for(int y=15;y>=0;y--){bool full=true;for(int x=0;x<10;x++)if(!g->grid[y][x])full=false;if(full){for(int j=y;j>0;j--)memcpy(g->grid[j],g->grid[j-1],20);memset(g->grid[0],0,20);g->score+=100;y++;}}vg_spawn(g);}
static void vg_step(VGState *g){
 if(g->paused||g->over||!g->kind)return;
 if(g->kind==1){static const int dx[]={-1,0,0,1},dy[]={0,1,-1,0};g->dir=g->next;int x=g->sx[0]+dx[g->dir],y=g->sy[0]+dy[g->dir];bool grow=x==g->food_x&&y==g->food_y;if(x<0||x>=20||y<0||y>=14){g->over=true;return;}for(int i=0;i<g->len-(grow?0:1);i++)if(g->sx[i]==x&&g->sy[i]==y){g->over=true;return;}int last=grow?g->len:g->len-1;for(int i=last;i>0;i--){g->sx[i]=g->sx[i-1];g->sy[i]=g->sy[i-1];}g->sx[0]=(unsigned char)x;g->sy[0]=(unsigned char)y;if(grow){g->len++;g->score+=10;vg_food(g);}}
 else if(g->kind==2){if(vg_fits(g,g->x,g->y+1))g->y++;else vg_lock(g);}
 else if(g->kind==5){g->ball_x+=g->dx;g->ball_y+=g->dy;if(g->ball_y<3||g->ball_y>177)g->dy=-g->dy;int target=(int)g->ball_y-20;g->enemy+=target>g->enemy?1:target<g->enemy?-1:0;if(g->enemy<0)g->enemy=0;if(g->enemy>140)g->enemy=140;if(g->dx<0&&g->ball_x<=10&&g->ball_y>=g->paddle&&g->ball_y<=g->paddle+40){g->ball_x=10;g->dx=-g->dx;g->score+=10;}if(g->dx>0&&g->ball_x>=270&&g->ball_y>=g->enemy&&g->ball_y<=g->enemy+40){g->ball_x=270;g->dx=-g->dx;}if(g->ball_x>280){g->score+=100;g->ball_x=140;g->dx=-2;}if(g->ball_x<0){g->lives--;g->ball_x=140;g->dx=2;if(!g->lives)g->over=true;}}
 else if(g->kind==3){g->ball_x+=g->dx;g->ball_y+=g->dy;if(g->ball_x<3){g->ball_x=3;g->dx=-g->dx;}if(g->ball_x>277){g->ball_x=277;g->dx=-g->dx;}if(g->ball_y<3){g->ball_y=3;g->dy=-g->dy;}if(g->dy>0&&g->ball_y>=165&&g->ball_y<=172&&g->ball_x>=g->paddle-3&&g->ball_x<=g->paddle+63){g->ball_y=165;g->dy=-g->dy;}int col=(int)g->ball_x/28,row=((int)g->ball_y-25)/14;if(g->ball_y>=25&&row>=0&&row<4&&col>=0&&col<10&&g->grid[row][col]){g->grid[row][col]=0;g->score+=10;g->dy=-g->dy;if(g->score==400)g->over=true;}if(g->ball_y>180)g->over=true;}
}
static void vg_control(VGState *g,int key){
 if(g->paused||g->over)return;
 if(g->kind==1){static const int opposite[]={3,2,1,0};if(key<4&&key>=0&&key!=opposite[g->dir])g->next=key;}
 else if(g->kind==2){if(key==0||key==3){int dx=key==0?-1:1;if(vg_fits(g,g->x+dx,g->y))g->x+=dx;}else if(key==1){vg_step(g);g->score++;}else if(key==2){int old=g->rotation;g->rotation=(old+1)%4;static const int kicks[]={0,-1,1,-2,2};bool fits=false;for(int i=0;i<5;i++)if(vg_fits(g,g->x+kicks[i],g->y)){g->x+=kicks[i];fits=true;break;}if(!fits)g->rotation=old;}else if(key==4){while(vg_fits(g,g->x,g->y+1)){g->y++;g->score+=2;}vg_lock(g);}}
 else if(g->kind==6){if(key>=0&&key<4)vg_tile_move(g,key);}
 else if(g->kind==5){g->paddle+=key==2?-15:key==1?15:0;if(g->paddle<0)g->paddle=0;if(g->paddle>140)g->paddle=140;}
 else if(g->kind==4){if(key==4)g->flag_mode=!g->flag_mode;}
 else if(g->kind==3){g->paddle+=key==0?-20:key==3?20:0;if(g->paddle<0)g->paddle=0;if(g->paddle>220)g->paddle=220;}
}
#endif
